// app/(os)/prospects/[id]/outreach/[outreach_id]/page.tsx
// Outreach review: view draft, edit, approve, then mark sent.
// Human approval gate — message_sent is NEVER populated by AI.

import Link from "next/link";
import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { Badge, Card, SectionTitle } from "@/app/_components/ui";
import { OutreachApprovalPanel } from "./OutreachApprovalPanel";

export const dynamic = "force-dynamic";

function statusTone(s: string): "green" | "amber" | "blue" | "neutral" {
  if (s === "Replied")  return "green";
  if (s === "Sent")     return "blue";
  if (s === "Approved") return "amber";
  return "neutral";
}

export default async function OutreachReviewPage({
  params,
}: {
  params: Promise<{ id: string; outreach_id: string }>;
}) {
  const { id: companyId, outreach_id } = await params;
  const supabase = createAdminClient();

  const { data: outreach, error } = await supabase
    .from("outreach")
    .select(`
      id, channel, status,
      message_draft, message_sent,
      drafted_at, approved_at, sent_at, replied_at,
      assessment_id,
      people (
        id, name, role, company_id,
        companies ( id, name )
      )
    `)
    .eq("id", outreach_id)
    .single();

  if (error || !outreach) notFound();

  const person  = outreach.people as { id: string; name: string; role: string } | null;
  const company = (outreach.people as { companies?: { name: string } } | null)?.companies;

  return (
    <div className="space-y-6 max-w-2xl">
      <Link href={`/prospects/${companyId}`} className="text-sm text-neutral-400 hover:text-neutral-700 underline">
        Back to {company?.name ?? "Company"}
      </Link>

      <div className="flex items-center gap-3 flex-wrap">
        <h1 className="text-xl font-bold text-neutral-900">Outreach Draft</h1>
        <Badge tone={statusTone(outreach.status ?? "Drafted")}>{outreach.status}</Badge>
        <Badge tone="neutral">{outreach.channel}</Badge>
      </div>

      {person && (
        <p className="text-sm text-neutral-500">
          To: <span className="font-medium text-neutral-800">{person.name}</span>
          {person.role && ` · ${person.role}`}
        </p>
      )}

      {/* ── Timeline chips ────────────────────────────────────────────────── */}
      <div className="flex flex-wrap gap-3 text-xs text-neutral-400">
        {outreach.drafted_at  && <span>Drafted {new Date(outreach.drafted_at).toLocaleDateString()}</span>}
        {outreach.approved_at && <span className="text-amber-600">Approved {new Date(outreach.approved_at).toLocaleDateString()}</span>}
        {outreach.sent_at     && <span className="text-blue-600">Sent {new Date(outreach.sent_at).toLocaleDateString()}</span>}
        {outreach.replied_at  && <span className="text-emerald-600">Replied {new Date(outreach.replied_at).toLocaleDateString()}</span>}
      </div>

      {/* ── AI draft ─────────────────────────────────────────────────────── */}
      <div className="space-y-2">
        <SectionTitle>AI Draft</SectionTitle>
        <Card>
          <p className="text-sm text-neutral-500 mb-3 italic text-xs">
            Generated by AI in Janine&apos;s voice. Review and edit before approving.
          </p>
          <p className="text-sm text-neutral-800 whitespace-pre-wrap leading-relaxed">
            {outreach.message_draft}
          </p>
        </Card>
      </div>

      {/* ── Sent copy (if already sent) ───────────────────────────────────── */}
      {outreach.message_sent && (
        <div className="space-y-2">
          <SectionTitle>Message Sent</SectionTitle>
          <Card className="border-blue-200 bg-blue-50">
            <p className="text-xs text-blue-600 mb-2 font-medium">This is the exact copy you sent.</p>
            <p className="text-sm text-neutral-800 whitespace-pre-wrap leading-relaxed">
              {outreach.message_sent}
            </p>
          </Card>
        </div>
      )}

      {/* ── Human approval gate ───────────────────────────────────────────── */}
      <OutreachApprovalPanel
        outreachId={outreach_id}
        companyId={companyId}
        currentStatus={outreach.status ?? "Drafted"}
        messageDraft={outreach.message_draft ?? ""}
      />
    </div>
  );
}
