-- Migration 0044 — Expand clients.industry_profile CHECK constraint
-- The original constraint only allowed: QSR, B2B, Retail, Other
-- The create-client form and cultural signal taxonomy use a broader set.
-- This migration expands it to match the full industry list used across the app.

-- Drop the old constraint (name is auto-generated by Postgres as <table>_<col>_check)
ALTER TABLE clients
  DROP CONSTRAINT IF EXISTS clients_industry_profile_check;

-- Add the expanded constraint
ALTER TABLE clients
  ADD CONSTRAINT clients_industry_profile_check
  CHECK (industry_profile IN (
    'QSR', 'B2B', 'Retail', 'Other',
    'FMCG', 'Financial Services', 'Telco',
    'Healthcare', 'Insurance', 'Automotive',
    'Hospitality', 'Media & Entertainment',
    'E-Commerce', 'Education', 'B2B SaaS'
  ));
